### ISSUE TITLE
while deving, properties don't appear for any actions

### ISSUE THREAD

**Issue by kennethkoontz** [dim-stream-deck/com.dim.streamdeck#14] opened 2024-07-30 18:20 UTC
See image:

![image](https://github.com/user-attachments/assets/123df586-f10a-4160-b8b8-ab3f056b4e51)

**Comment by fcannizzaro** [comment] 2024-08-02 22:02
Duplicate of #15

**Closed as completed by fcannizzaro** 2024-08-02 22:02 UTC
